name: Deploy Flask App

on:
  push:
    branches:
      - main  # Atau branch yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Sesuaikan dengan versi Python Anda

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Copy Files to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "app"  # Sesuaikan path di server

    - name: Restart App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /login
          # Perintah untuk restart app, misal menggunakan gunicorn
